---
title: 一人CSアドベントカレンダー・最終回
date: 2017-12-25T00:11:02+09:00
toc: true
tags: [AdC2017]
---

*これは[[https://qiita.com/advent-calendar/2017/myuon_myon_cs][一人Computer Scienceアドベントカレンダー]] 25日目の記事です。*

* くぅ疲

くぅ〜疲れましたw これにて完結です！

実は、一人アドベントカレンダーを一度くらいやってみたいなと思ったのが始まりでした

本当は話のネタなかったのですが←

ご厚意を無駄にするわけには行かないので自分の中の流行りのネタで挑んでみた所存ですw

以下、各テーマ達のみんなへのメッセジをどぞ(ここだけ原作無視)

- Isabelle基礎編(チュートリアル): 初心者に伝わる内容になってたらいいですね prog-prove読んでたら完全に知らないことが書いてあったりしたのでみなさん読みましょうね
- Isabelle実践編(IMP): IMPはネタとしては面白いんだけどbig-stepのdeterministicくらいだと内容的には面白みにかけるなという感想
- Isabelle応用編(ラムダ計算): SNまで示せたらドヤ顔できたんだけどね(CRも割としんどいけど)
- Haskell小ネタ: 本当に小ネタだった Isabelle編が当初の予定より長引いたせいで日数的には全然必要なかった
- Proof Assistant理論編: まとまりのない文章になった感すごい(いつものことや)
- Proof Assistant実践編: 実装はまぁ別にそんな面白いものでもないなって解説書いてて思った

* 感想

さて完走した感想(爆笑)ですが、まぁ事前に準備しとくのは大事だねと思いました。
今回はIsabelleの途中までは記事かきためてましたが、結局最後は前日の23時から描き始めるみたいなのが普通だったので書き溜めは大事だなみたいな。

それでも1日も落とさなかった(常に当日0時半までには投稿してた気がする)のはめっちゃ偉いと思います。

あと今年のAdCにもいくつかお誘いを頂いていたんですがまぁこっちがあったのとこっちの記事はシリーズものばかりだったので登録は見送りました。

来年は……ネタがあれば何か書きたいなと思います。一人アドベントカレンダーはしばらく大丈夫です。


* おわりに

こんな記事読む人いるんかってずっと思いながら書いてましたがもし読んでくれる人がいたならありがとうございました。

本当の本当に終わり[fn:1]

[fn:1] ってなんで俺くんが！？のところをやろうとしたら精神が持たなかったって言ったら「くぅ疲をやる覚悟が足りない」って言われました。そのとおりだと思います。

