---
title: 2017年振り返り
date: 2017-12-31T19:25:03+09:00
draft: true
tags: ["日記"]
toc: true
---

2017年が終わりそうなので([[http://myuon-myon.hatenablog.com/entry/2016/12/31/212403][去年の記事]])。

* アウトプット

** プログラミング&定理証明

github見たら意外と色々やってた。
古い順に

- [[https://github.com/myuon/DOTO][DOTO]]: todoリストをアレするwebアプリ。これは就活用に作ったような気がする。TypescriptとReactを使ってやっぱクライアントサイドはつらいって思った記憶。今ならElmとかで作ると思う。
- [[https://github.com/myuon/CatQ][CatQ]]: Coqによる圏論の形式化。Setoidベースでやったけど、圏論側で仮定したくなる公理の妥当性がCoqの上でも妥当なのかとかが無限に気になりやっぱ真面目にやるなら依存型使うのはダメだなと悟って放棄。
- [[https://github.com/myuon/dan][dan]]: やったことリストを登録してgithubの草みたいに表示したりするやつ。最近使ってない
- [[https://github.com/myuon/bwitterkuchen][bwitterkuchen]]: CUI Twitterクライアント。nyantreamを作ることにしたのでメンテはしてないけどしばらく使ってた。
- [[https://github.com/myuon/avix][avix]]: AviUtlという動画編集ソフトのexoファイルを生成するためのHaskellライブラリ。動画編集のときに使おうと思って作ってから一度も使ってない。
- [[https://github.com/myuon/sdlight][sdlight]]/[[https://github.com/myuon/widx][widx]]: sdlightはSDLのラッパーライブラリ(ゲームを作ろうとしてついでに作った)。widxはsdlightからwidgetだけを切り離してインターフェイスだけ提供するライブラリ、だったけどBackpackのバグが直らないので開発ができない状態になってる。
- [[https://github.com/myuon/nott][nott]]: Type Theoryに関するまとめノート的なものを置くところ(プログラミング関係ない)。今のバタバタが終わったらまた再開したい。
- [[https://github.com/myuon/typed][typed]]: 型付きラムダ計算の実装(TaPLみながら)と定理証明を雑に投げ込む場所。
- [[https://github.com/myuon/claire][claire]]: LKベースのproof assistant。今年の一人アドベントカレンダーでやったやつ。
- [[https://github.com/myuon/myuon.github.io][myuon.github.io]]: このブログ。今年入ってからはてなブログからgithub pagesでホスティングすることにし、今はhugoを使うのに落ち着いてる。
- [[https://github.com/myuon/nyantream][nyantream]]: CUIストリームクライアント(絶賛開発中)。時報/Twitter/Gmail/Slackに対応。GUI版も作りたい。

あと開発中のゲーム(最近開発してないけど)もあった。sdlight/widxが真面目に動くようになれば再開したいけどどうだろう。

** 絵

自分の中で二次創作という行為への折り合いが付き、二次創作を行えるようになったおかげか特に10月以降はかなり積極的に絵を描くようになった。
多分今年が一番絵が上手くなった(画力向上よりも魅せ方・道具の使い方的な意味で)1年だった気がする。

あとブログ漁ってたら今年の初めに[[http://myuon-myon.hatenablog.com/entry/2017/01/08/122301][新しいペンタブを買った]]ようなのでそのおかげもかなりある。
というか、今までラップトップしか持ってなかったのをデスクトップPCを買うのに合わせて21.5インチモニターを買ったので、画面が広くなるのに伴ってペンタブも大きくしたというのが正しい。
作業スペースが広くなるのは良さしかなかった。

最近は左手デバイス(キーボード)が欲しいお年ごろ。

** 動画編集

去年は色々やってたんだけど今年はあんまりやってない。
(AviUtlはwineでほぼ全機能が動くのに)ボイスロイドがwindowsでしか動かないせいで、動画編集とボイスロイドの録音が別PCでしないといけないのが結構つらいなになってきた。

windowsライセンス欲しい、買ってデスクトップPCの方に入れたい。

** ブログ

Github Pagesでブログをホスティングすることにしたので、emacsでブログがかけるようになり(今もorg-modeでかいてる)、少なくとも新しく記事を書くときの心理的障壁はだいぶ下がった。

そもそもブログ自体もうちょっと色々手を入れないと不便なところがあるのだけど、まぁemacsでほいほいかける環境は整えたので、頑張って書いていきたいなと思った。

一人アドベントカレンダーの時に確かにめっちゃ書いたけど、それ以外だとあんまり記事更新できてないので2018年はブログでアウトプットするのは積極的にやっていきたい。


* 生活的なこと

** 学生生活

割とずっと研究してた。結果が出ないつらさを知ったりした。

数学の研究は精神の健康に悪い。マジで悪い。

** デスクトップPCを買った

[[http://myuon-myon.hatenablog.com/entry/2017/02/15/000706][自作PC組んだよ2017]]

快適of快適になった。せっかくグラボ積んだのに(といっても大したアレじゃないけど)linux機なこととそもそも自分があんまりゲームやる人種じゃないせいで全然役に立ってないのがちょっともったいない感。

でも動画編集するときのエンコードは前に比べたら爆速になったのでそれはいいところ。

** コンテンツ消費

今年も去年に増してコンテンツにお金を投じたりした気がする。
何より今年の始めにデレステ初めて、課金もしたし1年間ほぼ途切れず続けてるのでここまで1つのコンテンツで長く遊んでいるのは中々珍しいなと思ったりしながら今日も遊んでた。
音ゲー楽しいなと思ったけどアーケードに手を出す勇気はない。

** プロジェクトマネジメント

結局本を1冊読んだだけなのだけれどプロジェクトマネジメントの勉強をした。
去年のまとめで、スケジュール管理の重要さを自覚した、とか方法論を身に着けたい、みたいなことが書いてあるけど、ちょうどそういうマネジメント的なことがずっと気になっていたのでいっちょ本でも読むかで本を読んでみたりした。

ただし個人の趣味的活動に企業のお仕事的プロジェクトマネジメントを持ち込んでもあまり上手く行かなそうなので、まだ何も活かせてはない。

この辺はもっと色々調べたり考えたりした上で2018年はマネジメントぢからをもっと磨いていきたい。


** 進路

就活は今年の6月くらいに終わった気がする([[http://myuon-myon.hatenablog.com/entry/2017/09/05/010318][これ]])。
なので来年4月からは就職して働き始めることになりそう。

働きたくはないがそれよりはお金が欲しい(というか必要)なのでしょうがない。



* まとめ

今年は、結構イレギュラーなことが多くて、「まぁこれがダメでもどうせ最後だし」とか「まぁこれは特別だからどう転んでもまぁいいや」とかそういうことが多かったので振り返りがやたら散漫としている。

来年からは環境が変わったりなどなどがあると思うので特にこうしたいああしたいという具体的な目標は立てにくいのだけれど、総括すると2017年は2016年に比べ、アウトプット・インプットのバランスがよかった1年だった(インプットに偏りすぎなかった)気がするので、来年もそういう感じでやっていきたい。

あと思ってること考えてることをもうちょっと外に出してもいいかなぁと。
ブログ記事にできるなーと思いながら文章かくのめんどくさくてやめたみたいなことが5億回くらいあったので雑でもいいから何か残るようにしときたい。


